### ISSUE TITLE
Spike Store

### ISSUE THREAD

**Issue by jwMaxwell** [jwMaxwell/Spike-2#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We will need to have some special even items (and regular items) for the Spike Store.
- On release day we will raise the bucks per message from 1 to 25
- Add early access roles (for early access to new features
- Double message bucks for special occasions
- Add message buck multipliers to the store
- Add "Founding Bulldog" role

**Describe alternatives you've considered**

**Additional context**

**Comment by brandoningli** [comment]
Proposed Pricing (assuming wallets will be pretty much wiped on launch):

- Founding Bulldog: $250
- Early Access: $5000
- Multipliers (maybe 2x, 3x, 4x): $10000 x (multiplier-1)

**Comment by brandoningli** [comment]
Role IDs:

- Founding Bulldog: `881016872324169768`
- Early Access: `881017418007343104`
- 4x Mult: `881017783578685471`
- 3x Mult: `881017704352481280`
- 2x Mult: `881017602263101470`

**Comment by brandoningli** [comment]
Code complete. PR #43 won't be merged to enable the items until launch.
