### ISSUE TITLE
Interpreter for User Added Features

### ISSUE THREAD

**Issue by brandoningli** [jwMaxwell/Spike-2#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Implement a code interpreter so users can add their own features right from within Spike and the server.

**Describe alternatives you've considered**

**Additional context**

**Comment by brandoningli** [comment]
- [x] Lisp Interpreter
- [x] Add features for server-specific tasks
- [ ] Add mechanism for permanent features/plugins

**Comment by brandoningli** [comment]
On Hold until @jwMaxwell determines the future of this interpreter.

**Comment by jwMaxwell** [comment]
- [ ] Add feature to allow users to read program arguments
- [ ] Add feature to allow users to create loops in their code
- [ ] Add feature to allow users to get information about the server

**Comment by brandoningli** [comment]
- [ ] Help and wiki for
  - [ ] mount
  - [ ] call
  - [ ] range
- [ ] loops? recursion?

**Comment by brandoningli** [comment]
Related: #23 and #24

**Comment by brandoningli** [comment]
Code complete.
